services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: ""
    startCommand: "python app.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: PUBLIC_URL
        sync: false
      - key: WEBHOOK_SECRET
        value: "super-secret-path"
