services:
  - type: web
    name: telegram-cleaner-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: PUBLIC_URL
        sync: false
      - key: WEBHOOK_SECRET
        value: super-secret-path
