services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: PUBLIC_URL
        sync: false
